# SEE: https://medium.com/swlh/easy-grafana-and-docker-compose-setup-d0f6f9fcec13
# SEE: https://github.com/jkehres/docker-compose-influxdb-grafana
version: "3"
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=5up3rS3cr3t
      - DOCKER_INFLUXDB_INIT_ORG=influxdata-org
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=5up3r-S3cr3t-auth-t0k3n
    restart: always
    privileged: true
  grafana:
    build:
      context: .
      dockerfile: Dockerfile-grafana
    container_name: grafana
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
    privileged: true

volumes:
  influxdb-storage:
  grafana-storage:
